import { useState, useEffect, useRef } from 'react'

import LogSection from '../components/LogSection'
import VideoSection from '../components/VideoSection'
import StatusSection from '../components/StatusSection'
import { useReelGeneration, generateDefaultInstruction } from '../hooks/useReelGeneration'
import ReelGeneratorForm from '../components/ReelGeneratorForm'

import './ReelGenerator.css'

function ReelGenerator() {
  const [productUrl, setProductUrl] = useState('')
  const [duration, setDuration] = useState(15)
  const [instruction, setInstruction] = useState('')
  const lastAutoGeneratedInstruction = useRef<string>('')

  // Generate default instruction when productUrl or duration changes
  // Only update if the current instruction matches the last auto-generated one
  // (i.e., user hasn't manually edited it)
  useEffect(() => {
    const defaultInstruction = generateDefaultInstruction(
      productUrl || null,
      duration
    )
    
    // Only update if instruction is empty or matches the last auto-generated instruction
    setInstruction((currentInstruction) => {
      if (!currentInstruction || currentInstruction === lastAutoGeneratedInstruction.current) {
        lastAutoGeneratedInstruction.current = defaultInstruction
        return defaultInstruction
      }
      return currentInstruction
    })
  }, [productUrl, duration])

  const {
    isGenerating,
    statusMessages,
    logEntries,
    videoUrl,
    videoInfo,
    generateReel,
    cancelGeneration,
  } = useReelGeneration()

  const handleGenerate = () => {
    // Build the full instruction from user's input
    // The instruction field contains the user's instructions text
    const userInstructions = instruction.trim()
    
    if (!userInstructions) {
      return
    }
    
    // Construct a clean prompt from the user's instructions
    const prompt = userInstructions.replace(/"/g, '\\"').replace(/\n/g, ' ')
    
    // Build the full instruction with tool call parameters
    let fullInstruction = `${userInstructions}\n\n`
    fullInstruction += `Call the generate_reel tool with these parameters:\n`
    fullInstruction += `- prompt: "${prompt}"\n`
    fullInstruction += `- time_range_seconds: ${duration}\n`
    
    if (productUrl) {
      fullInstruction += `- product_url: "${productUrl}"\n`
    }
    
    generateReel(fullInstruction)
  }

  const handleCancel = () => {
    cancelGeneration()
  }

  return (
    <div className="reel-generator">
      <div className="container">
        <div className="header">
          <h1>🎬 Reels Generator</h1>
          <p>Generate AI-powered reels using AgentLoop</p>
        </div>

        <div className="content">
          <ReelGeneratorForm
            productUrl={productUrl}
            duration={duration}
            instruction={instruction}
            isGenerating={isGenerating}
            onProductUrlChange={setProductUrl}
            onDurationChange={setDuration}
            onInstructionChange={setInstruction}
            onGenerate={handleGenerate}
            onCancel={handleCancel}
          />

          {statusMessages.length > 0 && (
            <StatusSection messages={statusMessages} />
          )}

          {videoUrl && (
            <VideoSection url={videoUrl} info={videoInfo} />
          )}

          {logEntries.length > 0 && (
            <LogSection entries={logEntries} />
          )}
        </div>
      </div>
    </div>
  )
}

export default ReelGenerator
