/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ContextEvaluatorFeedback } from './ContextEvaluatorFeedback';
import type { StatusResponse } from './StatusResponse';
import type { UserToolFailure } from './UserToolFailure';
import type { UserToolResponse } from './UserToolResponse';
export type WebsocketEvent = ({
    /**
     * Streamed reasoning or status updates from the agent.
     */
    ReasoningUpdate: string;
} | {
    /**
     * Result of a tool execution initiated by the agent.
     */
    ToolExecutionSuccess: UserToolResponse;
} | {
    ToolExecutionFailure: UserToolFailure;
} | {
    /**
     * Feedback from the background context evaluator.
     */
    ContextFeedback: ContextEvaluatorFeedback;
} | {
    /**
     * Current session status and optional time remaining.
     */
    StatusUpdate: StatusResponse;
} | {
    /**
     * The answer generated by the agent for the user, indicating if it's final.
     */
    AgentAnswer: {
        /**
         * The content of the answer.
         */
        content: string;
        /**
         * Flag indicating if this is the final answer for the current research goal.
         */
        is_final: boolean;
    };
} | {
    /**
     * A final research answer, typically including a title and detailed content.
     * Used when the agent signals the final answer (`LlmAgentResponse.is_final = true`).
     */
    ResearchAnswer: {
        /**
         * The full content of the final research report or answer.
         */
        content: string;
        /**
         * The title of the final research report or answer.
         */
        title: string;
    };
} | {
    /**
     * Indicates session completion, timeout, or forced termination.
     */
    SessionTerminated: {
        /**
         * An optional reason for the termination.
         */
        reason?: string | null;
        /**
         * The ID of the terminated session.
         */
        session_id: string;
    };
});

