use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        // Added for Invitations
        // Added for Organizations
        // Added for Webflow Creatives
        // Handler for InvitationsService error
        // Handlers for OrganizationService errors
        // Infinite Research
        // Shares
        // User Favorites
        //crate::routes::creatives::delete_webflow_creative::delete_webflow_creative,
        //crate::routes::creatives::generate_creative_webflow::generate_creative_webflow,
        //crate::routes::creatives::list_webflow_creatives::list_webflow_creatives,
        crate::routes::admin::users::create_user_handler::create_user_handler,
        crate::routes::admin::users::deactivate_user_handler::deactivate_user_handler,
        crate::routes::admin::users::impersonate_user_handler::impersonate_user_handler,
        crate::routes::admin::users::list_users_handler::list_users_handler,
        crate::routes::admin::users::update_user_handler::update_user_handler,
        crate::routes::admin::users::update_user_status_handler::update_user_status_handler,
        crate::routes::admin::users::update_user_credits_handler::update_user_credits_handler,
        crate::routes::admin::users::batch_create_users_handler::batch_create_users_handler,
        crate::routes::admin::users::batch_delete_users_handler::batch_delete_users_handler,
        crate::routes::admin::audit_logs::list_audit_logs_handler::list_audit_logs_handler,
        crate::routes::admin::audit_logs::get_audit_log_handler::get_audit_log_handler,
        crate::routes::admin::organizations::list_all_organizations_handler::list_all_organizations_handler,
        crate::routes::admin::organizations::admin_create_organization_handler::admin_create_organization_handler,
        crate::routes::admin::organizations::admin_update_organization_handler::admin_update_organization_handler,
        crate::routes::admin::organizations::update_organization_credits_handler::update_organization_credits_handler,
        crate::routes::admin::organizations::admin_add_members_handler::admin_add_members_handler,
        crate::routes::admin::organizations::admin_list_members_handler::admin_list_members_handler,
        crate::routes::admin::unlimited_access::grant_unlimited_to_user_handler::grant_unlimited_to_user_handler,
        crate::routes::admin::unlimited_access::revoke_unlimited_from_user_handler::revoke_unlimited_from_user_handler,
        crate::routes::admin::unlimited_access::list_unlimited_grants_handler::list_unlimited_grants_handler,
        crate::routes::api_keys::create_key_handler::create_key_handler,
        crate::routes::api_keys::delete_key_handler::delete_key_handler,
        crate::routes::api_keys::list_keys_handler::list_keys_handler,
        crate::routes::assets::create_asset::create_asset,
        crate::routes::assets::delete_asset::delete_asset,
        crate::routes::assets::get_asset_by_id::get_asset_by_id,
        crate::routes::assets::list_assets::list_assets,
        crate::routes::assets::patch_asset::patch_asset,
        crate::routes::assets::get_upload_url::get_upload_url,
        crate::routes::assets::confirm_upload::confirm_upload,
        crate::routes::assets::attach_assets::attach_assets,
        crate::routes::assets::detach_assets::detach_assets,
        crate::routes::assets::enhance_asset::enhance_asset,
        crate::routes::assets::quick_enhance_image::quick_enhance_image,
        crate::routes::assets::studio_graph::get_lineage_graph,
        crate::routes::lineage::get_lineage_graph_unified,
        crate::routes::auth::admin_password_reset::admin_password_reset,
        crate::routes::auth::change_password::change_password,
        crate::routes::auth::google_login::google_login,
        crate::routes::auth::google_callback::google_callback,
        crate::routes::auth::login::login,
        crate::routes::auth::logout::logout,
        crate::routes::auth::password_reset::password_reset,
        crate::routes::auth::register::register,
        crate::routes::auth::reset_password::reset_password,
        crate::routes::auth::verify_token::verify_token,
        crate::routes::auth::request_magic_link::request_magic_link,
        crate::routes::auth::verify_magic_link_token::verify_magic_link_token,
        crate::routes::bundles::create_bundle_handler::create_bundle,
        crate::routes::bundles::delete_bundle_handler::delete_bundle,
        crate::routes::bundles::get_bundle_handler::get_bundle_by_id,
        crate::routes::bundles::list_bundles_handler::list_bundles,
        crate::routes::bundles::update_bundle_handler::update_bundle,
        crate::routes::clone::clone_style::clone_style,
        crate::routes::collections::create_collection::create_collection,
        crate::routes::collections::delete_collection::delete_collection,
        crate::routes::collections::get_collection_by_id::get_collection_by_id,
        crate::routes::collections::list_collections::list_collections,
        crate::routes::collections::update_collection::update_collection,
        crate::routes::collections::get_collection_with_assets::get_collection_with_assets,
        crate::routes::collections::create_imageboard_board::create_imageboard_board,
        // Logo Collections routes
        crate::routes::logo_collections::create_logo_collection::create_logo_collection,
        crate::routes::logo_collections::delete_logo_collection::delete_logo_collection,
        crate::routes::logo_collections::get_logo_collection_by_id::get_logo_collection_by_id,
        crate::routes::logo_collections::list_logo_collections::list_logo_collections,
        crate::routes::logo_collections::update_logo_collection::update_logo_collection,
        crate::routes::logo_collections::add_asset_to_logo_collection::add_asset_to_logo_collection,
        crate::routes::logo_collections::remove_asset_from_logo_collection::remove_asset_from_logo_collection,
        // Watermarking routes
        crate::routes::watermarking::apply_batch_watermark::apply_batch_watermark,
        crate::routes::creatives::create_creative::create_creative,
        crate::routes::creatives::delete_creative::delete_creative,
        crate::routes::creatives::discard_draft::discard_draft,
        crate::routes::creatives::duplicate_creative::duplicate_creative,
        crate::routes::creatives::edit_creative::edit_creative,
        crate::routes::creatives::generate_creative::generate_creative,
        crate::routes::creatives::get_creative_by_id::get_creative_by_id,
        crate::routes::creatives::get_creative_content::get_creative_content,
        crate::routes::creatives::list_creatives::list_creatives,
        crate::routes::creatives::publish_draft::publish_draft,
        crate::routes::creatives::update_creative_name::update_creative_name,
        crate::routes::dashboard::daily_activity_stats::get_daily_activity_stats,
        crate::routes::dashboard::baseline_count::get_baseline_count,
        crate::routes::dashboard::kpi_summary::get_kpi_summary,
        crate::routes::dashboard::usage_statistics::get_usage_statistics,
        crate::routes::dashboard::custom_events_stats::get_custom_events_stats,
        crate::routes::dashboard::custom_events_stats::get_custom_events_daily_stats,
        crate::routes::dashboard::custom_events_stats::get_cohort_registration_analysis,
        crate::routes::dashboard::user_cohort_analysis::get_user_cohort_analysis_handler,
        crate::routes::documents::copy_document::copy_document,
        crate::routes::documents::create_document::create_document,
        crate::routes::documents::delete_document::delete_document,
        crate::routes::documents::get_document_by_id::get_document_by_id,
        crate::routes::documents::get_document_by_name::get_document_by_name,
        crate::routes::documents::get_prefill_documents::get_prefill_documents, // Moved from research
        crate::routes::documents::list_documents::list_documents,
        crate::routes::documents::list_vocal_tour_documents::list_vocal_tour_documents,
        crate::routes::documents::update_document::update_document,
        crate::routes::documents::toggle_document_research::toggle_document_research,
        crate::routes::documents::upload_and_attach::upload_and_attach,
        // Content Studio routes
        crate::routes::content_studio::transform_document::transform_document,
        crate::routes::content_studio::generate_content::generate_content,
        crate::routes::content_studio::get_document_lineage::get_document_lineage,
        crate::routes::content_studio::create_document_journey::create_document_journey,
        crate::routes::content_studio::add_document_to_journey::add_document_to_journey,
        crate::routes::content_studio::get_document_journey::get_document_journey_by_document_id,
        crate::routes::content_studio::get_journey_by_id::get_journey_by_id,
        crate::routes::content_studio::delete_document::delete_content_studio_document,
        crate::routes::content_studio::list_template_documents::list_template_documents,
        crate::routes::content_studio::upload_template_document::upload_template_document,
        crate::routes::files::upload_file::upload_file,
        crate::routes::formats::copy_custom_creative_format::copy_custom_creative_format,
        crate::routes::formats::create_custom_creative_format::create_custom_creative_format,
        crate::routes::formats::delete_custom_creative_format::delete_custom_creative_format,
        crate::routes::formats::list_custom_creative_formats::list_custom_creative_formats,
        crate::routes::formats::update_custom_creative_format::update_custom_creative_format,
        crate::routes::health::health_check,
        crate::routes::environment::get_environment_variables,
        crate::routes::infinite_researches::create_infinite_research::create_infinite_research,
        crate::routes::infinite_researches::delete_infinite_research::delete_infinite_research,
        crate::routes::infinite_researches::get_execution_log::get_execution_log,
        crate::routes::infinite_researches::get_infinite_research::get_infinite_research,
        crate::routes::infinite_researches::list_infinite_research_executions::list_infinite_research_executions,
        crate::routes::infinite_researches::list_infinite_researches::list_infinite_researches,
        crate::routes::infinite_researches::update_infinite_research::update_infinite_research,
        crate::routes::infinite_researches::update_infinite_research_status::update_infinite_research_status,
        crate::routes::infinite_researches::run_infinite_research_manually::run_infinite_research_manually,
        crate::routes::internal::run_infinite_research::run_infinite_research,
        crate::routes::one_time_researches::create_one_time_research::create_one_time_research,
        crate::routes::one_time_researches::get_one_time_research::get_one_time_research,
        crate::routes::one_time_researches::list_one_time_researches::list_one_time_researches,
        crate::routes::invitations::accept_invitation_handler::accept_invitation_handler,
        crate::routes::invitations::list_pending_invitations_handler::list_pending_invitations_handler,
        crate::routes::one_time_researches::delete_one_time_research::delete_one_time_research,
        crate::routes::invitations::reject_invitation_handler::reject_invitation_handler,
        crate::routes::organizations::create_organization_handler::create_organization_handler,
        crate::routes::organizations::delete_organization_handler::delete_organization_handler,
        crate::routes::organizations::get_organization_members_for_credits::get_organization_members_handler,
        crate::routes::organizations::invite_member_handler::invite_member_handler,
        crate::routes::organizations::list_members_handler::list_members_handler,
        crate::routes::organizations::list_organizations_handler::list_organizations_handler,
        crate::routes::organizations::list_sent_invitations_handler::list_sent_invitations_handler,
        crate::routes::organizations::update_organization_handler::update_organization_handler,
        crate::routes::organizations::remove_member_handler::remove_member_handler,
        crate::routes::requests::delete_request::delete_request,
        crate::routes::requests::get_request_by_id::get_request_by_id,
        crate::routes::requests::list_requests::list_requests,
        crate::routes::research_conversations::create_conversation::create_conversation,
        crate::routes::research_conversations::delete_conversation::delete_conversation, // Added this line
        crate::routes::research_conversations::get_conversation::get_conversation,
        crate::routes::research_conversations::list_conversations_by_document::list_conversations_by_document,
        crate::routes::research_conversations::update_conversation_state::update_conversation_state, // Already seems to be here, ensuring it is
        crate::routes::shares::create_share::create_share,
        crate::routes::shares::delete_share::delete_share,
        crate::routes::shares::list_shares::list_shares,
        crate::routes::stripe::webhooks::stripe_webhook_handler,
        // Billing routes - updated to match current implementation
        crate::routes::billing::checkout::create_checkout_session,
        crate::routes::billing::checkout::update_checkout_session,
        crate::routes::billing::portal::create_customer_portal_session,
        crate::routes::billing::plans::get_plans,
        crate::routes::billing::products::get_products,
        crate::routes::users::subscriptions::get_current_user_subscription,
        crate::routes::billing::get_billing_status_handler::get_billing_status_handler,
        crate::routes::billing::get_payment_status_handler::get_payment_status_handler,
        crate::routes::styles::create_style::create_style,
        crate::routes::styles::create_style_from_creative::create_style_from_creative,
        crate::routes::styles::delete_style::delete_style,
        crate::routes::styles::get_style_by_id::get_style_by_id,
        crate::routes::styles::list_styles::list_styles,
        crate::routes::styles::update_style::update_style,
        crate::routes::user_db_collections::create_user_db_collection::create_user_db_collection,
        crate::routes::user_db_collections::delete_user_db_collection::delete_user_db_collection,
        crate::routes::user_db_collections::get_user_db_collection::get_user_db_collection,
        crate::routes::user_db_collections::items::create_user_db_collection_item::create_user_db_collection_item,
        crate::routes::user_db_collections::items::delete_user_db_collection_item::delete_user_db_collection_item,
        crate::routes::user_db_collections::items::get_user_db_collection_item::get_user_db_collection_item,
        crate::routes::user_db_collections::items::list_user_db_collection_items::list_user_db_collection_items,
        crate::routes::user_db_collections::items::update_user_db_collection_item::update_user_db_collection_item,
        crate::routes::user_db_collections::list_user_db_collections::list_user_db_collections,
        crate::routes::user_db_collections::update_user_db_collection::update_user_db_collection,
        crate::routes::user_db_collections::update_user_db_collection_schema::update_user_db_collection_schema,
        crate::routes::user_favorites::create_favorite::create_favorite,
        crate::routes::user_favorites::delete_favorite::delete_favorite,
        crate::routes::user_favorites::list_favorites::list_favorites,
        crate::routes::user_favorites::toggle_favorite::toggle_favorite,
        crate::routes::user_favorites::add_favorite_prompt::add_favorite_prompt,
        crate::routes::user_favorites::list_favorite_prompts::list_favorite_prompts,
        crate::routes::user_favorites::remove_favorite_prompt::remove_favorite_prompt,
        // Predefined Collections
        crate::routes::predefined_collections::create_predefined_collection::create_predefined_collection,
        crate::routes::predefined_collections::list_predefined_collections::list_predefined_collections,
        crate::routes::predefined_collections::get_predefined_collection::get_predefined_collection,
        crate::routes::predefined_collections::update_predefined_collection::update_predefined_collection,
        crate::routes::predefined_collections::delete_predefined_collection::delete_predefined_collection,
        // PDF Conversion
        crate::routes::pdf_conversion::convert_to_pdf,
        crate::routes::pdf_conversion::convert_creative_to_pdf,
        crate::routes::vocal_tour::create_vocal_tour::create_vocal_tour,
        crate::routes::vocal_tour::delete_vocal_tour::delete_vocal_tour,
        crate::routes::vocal_tour::get_vocal_tour::get_vocal_tour,
        crate::routes::vocal_tour::list_vocal_tours::list_vocal_tours,
        crate::routes::vocal_tour::get_vocal_tour_by_document::get_vocal_tour_by_document,
        crate::routes::vocal_tour::attach_to_listing::attach_vocal_tour_to_listing,
        crate::routes::vocal_tour::get_vocal_tour_assets::get_vocal_tour_assets,
        crate::routes::property_contents::create_property_contents::create_property_contents,
        crate::routes::property_contents::create_property_contents_with_studio_journey::create_property_contents_with_studio_journey,
        // Studio Journey Shares
        crate::routes::studio_journey_shares::create_share::create_share,
        crate::routes::studio_journey_shares::get_share::get_share,
        crate::routes::studio_journey_shares::delete_share::delete_share,
        // Studio Tutorial Events
        crate::routes::studio::tutorial_events::log_tutorial_button_click,
        crate::routes::public::view_journey::view_journey,
        // Feed routes
        crate::routes::feed::create_post::create_feed_post,
        crate::routes::feed::get_feed::get_feed,
        crate::routes::feed::get_post::get_feed_post,
        crate::routes::feed::update_post::update_feed_post,
        crate::routes::feed::delete_post::delete_feed_post,
        // User endpoints
        crate::routes::users::get_current_user_handler::get_current_user_handler,
        // User credit management
        crate::routes::users::user_credit_handlers::claim_daily_credits_handler,
        crate::routes::users::user_credit_handlers::get_user_credits_handler,
        crate::routes::users::get_credit_usage_history::get_credit_usage_history_handler,
        crate::routes::users::get_action_type_breakdown::get_action_type_breakdown_handler,
        crate::routes::users::get_organization_user_credit_breakdown::get_organization_user_credit_breakdown_handler,
        // Credit rewards endpoints
        crate::routes::credit_rewards::get_reward_definitions::get_reward_definitions,
        crate::routes::credit_rewards::get_user_rewards::get_user_credit_rewards,
        crate::routes::credit_rewards::claim_reward::claim_reward,
        // Mobile Analytics
        crate::routes::analytics::track_mobile_event::track_mobile_event,
        // Dub attribution tracking endpoints
        crate::routes::dub::track_lead::track_lead,
        crate::routes::dub::generate_referral_token::generate_referral_token,
        // Imageboard webhook endpoints
        crate::routes::imageboard::get_organization_balance::get_organization_balance,
        crate::routes::imageboard::bulk_deduct_credit_transaction::bulk_deduct_credit_transaction,
   ),
   components(
       schemas(
            crate::auth::scheduler_token::InfiniteResearchClaims,
            crate::db::api_keys::ApiKeyMetadata,
            crate::db::assets::Asset,
            crate::db::assets::AssetWithProvenance,
            crate::db::bundles::Bundle,
            crate::db::collections::Collection,
            crate::db::creatives::Creative,
            crate::db::custom_creative_formats::CustomCreativeFormat,
            crate::db::document_research_usage::DocumentResearchUsage, // Added new enum
            crate::db::documents::Document,
            crate::db::favorites::FavoriteEntityType,
            crate::db::favorites::UserFavorite,
            crate::db::infinite_research::InfiniteResearch,
            crate::db::infinite_research_execution::InfiniteResearchExecution,
            crate::db::one_time_research::OneTimeResearch,
            crate::db::organization_members::OrganizationMember,
            crate::db::organizations::Organization,
            crate::db::pending_invitations::PendingInvitation,
            crate::db::pending_invitations::PendingInvitationResponse,
            crate::db::requests::RequestRecord,
            crate::db::research_conversation::ResearchConversation,
            crate::db::shares::ObjectShare,
            crate::db::styles::Style,
            crate::db::users::PublicUser,
            crate::routes::users::me_response::MeResponse,
            crate::routes::users::me_response::OrganizationCreditInfo,
            crate::db::webflow_creatives::WebflowCreative,
            crate::db::credit_transaction::CreditTransaction,
            crate::queries::credit_transactions::CreditUsagePoint,
            crate::queries::credit_transactions::ActionTypeBreakdown,
            crate::queries::credit_transactions::UserCreditUsageSummary,
            crate::queries::dashboard::query_kpi_metrics::KpiMetric,
            crate::queries::dashboard::query_usage_statistics::UsageStatisticsItem,
            crate::routes::admin::users::create_user_request::CreateUserRequest,
            crate::routes::admin::users::impersonate_user_response::ImpersonateUserResponse,
            crate::routes::admin::users::list_users_params::ListUsersParams,
            crate::routes::admin::users::list_users_response::ListUsersResponse,
            crate::routes::admin::users::update_user_request::UpdateUserRequest,
            crate::routes::admin::users::batch_create_users_request::BatchCreateUsersRequest,
            crate::routes::admin::users::batch_create_users_response::BatchCreateUsersResponse,
            crate::routes::admin::users::batch_create_users_response::UserCreateSuccess,
            crate::routes::admin::users::batch_create_users_response::UserCreateFailure,
            crate::routes::admin::users::batch_delete_users_request::BatchDeleteUsersRequest,
            crate::routes::admin::users::batch_delete_users_response::BatchDeleteUsersResponse,
            crate::routes::admin::users::batch_delete_users_response::UserDeleteSuccess,
            crate::routes::admin::users::batch_delete_users_response::UserDeleteFailure,
            crate::routes::admin::audit_logs::list_audit_logs_params::ListAuditLogsParams,
            crate::routes::admin::audit_logs::list_audit_logs_response::ListAuditLogsResponse,
            crate::db::audit_logs::AuditLog,
            crate::routes::admin::organizations::list_all_organizations_params::ListAllOrganizationsParams,
            crate::routes::admin::organizations::list_all_organizations_response::ListAllOrganizationsResponse,
            crate::routes::admin::organizations::list_all_organizations_response::EnrichedOrganizationDto,
            crate::routes::admin::organizations::admin_create_organization_request::AdminCreateOrganizationRequest,
            crate::routes::admin::organizations::admin_update_organization_request::AdminUpdateOrganizationRequest,
            crate::routes::admin::organizations::admin_add_members_request::AdminAddMembersRequest,
            crate::routes::admin::organizations::admin_add_members_response::AdminAddMembersResponse,
            crate::routes::admin::organizations::admin_add_members_response::MemberAddSuccess,
            crate::routes::admin::organizations::admin_add_members_response::MemberAddFailure,
            crate::db::unlimited_access_grant::UnlimitedAccessGrant,
            crate::routes::admin::unlimited_access::grant_unlimited_to_user_request::GrantUnlimitedToUserRequest,
            crate::routes::admin::unlimited_access::grant_unlimited_to_user_response::GrantUnlimitedToUserResponse,
            crate::routes::admin::unlimited_access::revoke_unlimited_from_user_request::RevokeUnlimitedFromUserRequest,
            crate::routes::admin::unlimited_access::revoke_unlimited_from_user_response::RevokeUnlimitedFromUserResponse,
            crate::routes::admin::unlimited_access::list_unlimited_grants_params::ListUnlimitedGrantsParams,
            crate::routes::admin::unlimited_access::list_unlimited_grants_response::ListUnlimitedGrantsResponse,
            crate::routes::api_keys::create_api_key_request::CreateApiKeyRequest,
            crate::routes::api_keys::create_api_key_response::CreateApiKeyResponse,
            crate::routes::api_keys::list_keys_params::ListApiKeysParams,
            crate::routes::api_keys::list_keys_response::ApiKeyWithUserDetails,
            crate::routes::assets::create_asset_request::CreateAssetRequest,
            crate::routes::assets::list_assets::ListAssetsParams,
            crate::routes::assets::get_upload_url_request::GetUploadUrlRequest,
            crate::routes::assets::get_upload_url_response::GetUploadUrlResponse,
            crate::routes::assets::confirm_upload_request::ConfirmUploadRequest,
            crate::routes::assets::confirm_upload_response::ConfirmUploadResponse,
            crate::routes::assets::responses::AssetWithCollection,
            crate::routes::assets::responses::ListAssetsWithCollectionResponse,
            crate::routes::assets::attach_assets::AttachAssetsRequest,
            crate::routes::assets::detach_assets::DetachAssetsRequest,
            crate::routes::assets::enhance_asset_request::EnhanceAssetRequest,
            crate::routes::assets::enhance_asset_response::EnhanceAssetResponse,
            crate::routes::assets::quick_enhance_image_request::QuickEnhanceImageRequest,
            crate::routes::assets::quick_enhance_image_response::QuickEnhanceImageResponse,
            crate::routes::auth::change_password_request::ChangePasswordRequest,
            crate::routes::auth::login_request::LoginRequest,
            crate::routes::auth::login_response::LoginResponse,
            crate::routes::auth::logout_response_body::LogoutResponseBody,
            crate::routes::auth::password_reset_request::PasswordResetRequest,
            crate::routes::auth::register_request::RegisterRequest,
            crate::routes::auth::reset_password_request::ResetPasswordRequest,
            crate::routes::auth::standard_logout_response::StandardLogoutResponse,
            crate::routes::auth::stop_impersonation_response::StopImpersonationResponse,
            crate::routes::auth::verify_token_response::VerifyTokenResponse,
            crate::routes::auth::request_magic_link::MagicLinkRequest,
            crate::routes::auth::request_magic_link::MagicLinkResponse,
            crate::routes::auth::verify_magic_link_token_request::VerifyMagicLinkTokenRequest,
            crate::routes::auth::verify_magic_link_token_response::VerifyMagicLinkTokenResponse,
            crate::auth::tokens::magic_link_claims::MagicLinkClaims,
            crate::routes::bundles::create_bundle_request::CreateBundleRequest,
            crate::routes::bundles::list_bundles_response::ListExpandedBundlesResponse,
            crate::routes::bundles::update_bundle_request::UpdateBundleRequest,
            crate::routes::clone::clone_request::CloneRequest,
            crate::routes::clone::clone_response::CloneResponse,
            crate::routes::collections::create_collection_request::CreateCollectionRequest,
            crate::routes::collections::responses::CollectionWithPermissions,
            crate::routes::collections::responses::ListCollectionsWithPermissionsResponse,
            crate::queries::collections::get_collection_with_assets::CollectionWithAssets,
            // Logo Collections schemas
            crate::db::logo_collection::LogoCollection,
            crate::db::logo_collection_asset::LogoCollectionAsset,
            crate::db::watermarking_job::WatermarkingJob,
            crate::schemas::logo_collection_schemas::CreateLogoCollectionRequest,
            crate::schemas::logo_collection_schemas::UpdateLogoCollectionRequest,
            crate::schemas::logo_collection_schemas::AddAssetToCollectionRequest,
            crate::schemas::logo_collection_schemas::LogoCollectionResponse,
            crate::schemas::logo_collection_schemas::LogoCollectionSummaryResponse,
            crate::routes::logo_collections::list_logo_collections::ListLogoCollectionsResponse,
            // Watermarking schemas
            crate::schemas::watermark_schemas::WatermarkConfig,
            crate::schemas::watermark_schemas::WatermarkPosition,
            crate::schemas::watermark_schemas::WatermarkSize,
            crate::schemas::watermark_schemas::CornerPosition,
            crate::schemas::watermark_schemas::EdgePosition,
            crate::schemas::watermark_schemas::ApplyWatermarkRequest,
            crate::schemas::watermark_schemas::ApplyBatchWatermarkRequest,
            crate::schemas::watermark_schemas::WatermarkDefinition,
            crate::schemas::watermark_schemas::WatermarkResponse,
            crate::schemas::watermark_schemas::WatermarkJobResponse,
            crate::routes::creatives::create_creative_request::CreateCreativeRequest,
            crate::routes::creatives::edit_creative_request::EditCreativeRequest,
            crate::routes::creatives::generate_creative_request::GenerateCreativeRequest,
            crate::routes::creatives::get_creative_content_response::GetCreativeContentResponse,
            crate::routes::creatives::update_creative_name_request::UpdateCreativeNameRequest,
            crate::routes::dashboard::chart_models::ChartData,
            crate::routes::dashboard::chart_models::ChartSeries,
            crate::routes::dashboard::daily_activity_stats::DailyActivityParams,
            crate::routes::dashboard::baseline_count::BaselineCountParams,
            crate::routes::dashboard::baseline_count::BaselineCountResponse,
            crate::routes::dashboard::custom_events_stats::CustomEventsStatsParams,
            crate::routes::dashboard::custom_events_stats::CustomEventsDailyStatsParams,
            crate::routes::dashboard::custom_events_stats::CohortRegistrationAnalysisParams,
            crate::routes::dashboard::custom_events_stats::CohortRegistrationAnalysisResponse,
            crate::routes::dashboard::custom_events_stats::CohortDimensionStat,
            crate::routes::dashboard::kpi_summary::KpiParams,
            crate::routes::dashboard::kpi_summary::KpiSummaryResponse,
            crate::routes::dashboard::series_data_point::SeriesDataPoint,
            crate::routes::dashboard::usage_statistics::ListUsageStatisticsResponse,
            crate::routes::dashboard::usage_statistics::TimeFrame,
            crate::routes::dashboard::usage_statistics::UsageStatisticsParams,
            crate::routes::dashboard::user_cohort_analysis::UserCohortAnalysisParams,
            crate::routes::dashboard::user_cohort_analysis::UserCohortAnalysisResponse,
            crate::routes::dashboard::user_cohort_analysis::CohortSummary,
            crate::routes::dashboard::user_cohort_analysis::AssetActivities,
            crate::routes::dashboard::user_cohort_analysis::OtherActivities,
            crate::routes::dashboard::user_cohort_analysis::ActivityMetrics,
            crate::routes::dashboard::user_cohort_analysis::DailyActivityPoint,
            crate::routes::documents::create_document_request::CreateDocumentRequest,
            crate::routes::documents::list_vocal_tour_documents::ListVocalTourDocumentsParams,
            crate::routes::documents::list_vocal_tour_documents::ListVocalTourDocumentsResponse,
            crate::routes::documents::responses::DocumentResponse,
            crate::routes::documents::responses::DocumentResponseWithFavorite,
            crate::routes::documents::toggle_document_research::ToggleDocumentResearchRequest,
            crate::routes::documents::update_document_request::UpdateDocumentRequest,
            crate::routes::documents::upload_and_attach::UploadAndAttachResponse,
            // Content Studio schemas
            crate::routes::content_studio::requests::TransformDocumentRequest,
            crate::routes::content_studio::requests::GenerateContentRequest,
            crate::routes::content_studio::requests::DocumentLineageRequest,
            crate::routes::content_studio::requests::ListTemplateDocumentsParams,
            crate::routes::content_studio::responses::ContentGenerationResponse,
            crate::routes::content_studio::responses::DocumentLineageResponse,
            crate::routes::content_studio::responses::DocumentLineageNode,
            crate::routes::content_studio::responses::DocumentLineageEdge,
            crate::routes::content_studio::responses::AvailableModelsResponse,
            crate::routes::content_studio::responses::ContentServiceHealthResponse,
            crate::routes::content_studio::responses::ListTemplateDocumentsResponse,
            crate::routes::content_studio::create_document_journey::CreateDocumentJourneyRequest,
            crate::routes::content_studio::create_document_journey::DocumentJourneyResponse,
            crate::routes::content_studio::add_document_to_journey::AddDocumentToJourneyRequest,
            crate::routes::content_studio::add_document_to_journey::DocumentNodeResponse,
            crate::routes::content_studio::get_document_journey::JourneyNodeResponse,
            crate::routes::content_studio::get_document_journey::DocumentJourneyWithNodesResponse,
            crate::routes::content_studio::get_journey_by_id::DocumentJourneyByIdResponse,
            // Content Studio lineage types
            crate::queries::documents::lineage::types::DocumentGraph,
            crate::queries::documents::lineage::types::DocumentGraphNode,
            crate::queries::documents::lineage::types::DocumentGraphEdge,
            crate::queries::documents::lineage::types::DocumentDerivationParams,
            crate::queries::documents::lineage::types::DocumentTransformationParams,
            crate::routes::error_response::ErrorResponse,
            crate::routes::files::file_upload_request::FileUpload,
            crate::routes::formats::create_custom_format_request::CreateCustomFormatRequest,
            crate::routes::infinite_researches::create_infinite_research_request::CreateInfiniteResearchRequest,
            crate::routes::infinite_researches::update_infinite_research_request::UpdateInfiniteResearchRequest,
            crate::routes::infinite_researches::update_infinite_research_status_request::UpdateInfiniteResearchStatusRequest,
            crate::routes::infinite_researches::list_infinite_researches::InfiniteResearchListItem,
            crate::routes::one_time_researches::create_one_time_research_request::CreateOneTimeResearchRequest,
            crate::routes::invitations::accept_invitation_handler::AcceptInvitationRequest,
            crate::routes::invitations::reject_invitation_handler::RejectInvitationRequest,
            crate::routes::organizations::create_organization_request::CreateOrganizationRequest,
            crate::routes::organizations::invite_member_handler::InviteMemberRequest,
            crate::routes::organizations::list_members_handler::ListMembersResponse,
            crate::routes::organizations::list_organizations_handler::ListOrganizationsResponse,
            crate::routes::organizations::list_sent_invitations_handler::ListSentInvitationsApiResponse,
            crate::routes::organizations::list_sent_invitations_handler::SentInvitationDetails,
            crate::routes::organizations::member_response::OrganizationMemberResponse,
            crate::routes::organizations::update_organization_request::UpdateOrganizationRequest,
            crate::routes::requests::DeleteRequestResponse,
            crate::routes::requests::GetRequestResponse,
            crate::routes::requests::ListRequestsResponse,
            crate::routes::research_conversations::create_research_conversation_request::CreateResearchConversationRequest,
            crate::routes::research_conversations::update_research_conversation_state_request::UpdateResearchConversationStateRequest,
            crate::routes::shares::create_share_request::CreateShareRequest,
            crate::routes::shares::list_shares::ListSharesParams,
            crate::routes::shares::list_shares::ListSharesResponse,
            crate::routes::styles::create_style_from_creative_request::CreateStyleFromCreativeRequest,
            crate::routes::styles::create_style_request::CreateStyleRequest,
            crate::routes::styles::list_styles::ListStylesResponse,
            crate::routes::styles::responses::StyleResponse,
            crate::routes::styles::responses::StyleResponseWithFavorite,
            crate::routes::styles::update_style_request::UpdateStyleRequest,
            crate::routes::user_favorites::create_favorite_request::CreateFavoriteRequest,
            crate::routes::user_favorites::entity_relations::EntityData,
            crate::routes::user_favorites::favorite_with_entity::FavoriteWithEntity,
            crate::routes::user_favorites::list_favorites::ListFavoritesParams,
            crate::routes::user_favorites::list_favorites::ListFavoritesResponse,
            crate::routes::user_favorites::toggle_favorite::ToggleFavoriteResponse,
            crate::types::expanded_bundle::ExpandedBundle,
            // Predefined Collections
            crate::db::predefined_collection::PredefinedCollection,
            crate::routes::predefined_collections::create_predefined_collection_request::CreatePredefinedCollectionRequest,
            crate::routes::predefined_collections::update_predefined_collection_request::UpdatePredefinedCollectionRequest,
            crate::routes::predefined_collections::list_predefined_collections::ListPredefinedCollectionsParams,
            crate::routes::predefined_collections::list_predefined_collections::ListPredefinedCollectionsResponse,
            crate::routes::predefined_collections::get_predefined_collection::PredefinedCollectionWithMetadata,
            crate::db::user_db_collection::UserDbCollection,
            crate::routes::user_db_collections::get_or_create_user_collection_by_predefined::GetOrCreateUserCollectionResponse,
            crate::routes::user_db_collections::get_or_create_user_collection_by_predefined_name::GetOrCreateUserCollectionByNameResponse,
            crate::db::user_db_collection_item::UserDbCollectionItem,
            // PDF Conversion
            crate::routes::pdf_conversion::ConvertToPdfRequest,
            crate::routes::pdf_conversion::PdfConversionError,
            crate::routes::environment::EnvironmentResponse,
            // Billing schemas - updated to match current implementation
            crate::routes::billing::checkout::CreateCheckoutSessionRequest,
            crate::routes::billing::checkout::CreateCheckoutSessionResponse,
            crate::routes::billing::portal::CreateCustomerPortalSessionRequest,
            crate::routes::billing::portal::CreateCustomerPortalSessionResponse,
            crate::routes::billing::plans::GetPlansQuery,
            crate::services::billing::stripe_client::StripeProduct,
            crate::services::billing::stripe_client::StripePrice,
            crate::services::billing::stripe_client::StripePriceTier,
            crate::services::billing::stripe_client::StripeTransformQuantity,
            crate::services::billing::stripe_client::StripeCustomUnitAmount,
            crate::services::billing::stripe_client::StripeMarketingFeature,
            crate::services::billing::stripe_client::StripePackageDimensions,
            crate::services::billing::stripe_client::StripeRecurring,
            crate::services::billing::stripe_client::StripeBillingSchema,
            crate::services::billing::stripe_client::StripePlan,
            crate::services::billing::stripe_client::StripePlanWithProduct,
            crate::services::billing::stripe_client::StripeCustomer,
            crate::services::billing::stripe_client::StripeSubscription,
            crate::services::billing::stripe_client::StripeSubscriptionItems,
            crate::services::billing::stripe_client::StripeSubscriptionItem,
            crate::db::user_subscription::UserSubscription,
            crate::db::user_credit_allocation::UserCreditAllocation,
            crate::routes::billing::billing_status_response::BillingStatusResponse,
            crate::routes::billing::payment_status_response::PaymentStatusResponse,
            crate::routes::billing::access_source::AccessSource,
            crate::db::payment_completions::PaymentCompletion,
            crate::routes::vocal_tour::create_vocal_tour_request::CreateVocalTourRequest,
            crate::routes::vocal_tour::create_vocal_tour_response::CreateVocalTourResponse,
            crate::routes::vocal_tour::attach_to_listing_request::AttachVocalTourToListingRequest,
            crate::routes::vocal_tour::attach_to_listing_response::AttachVocalTourToListingResponse,
            crate::routes::vocal_tour::list_vocal_tours_params::ListVocalToursParams,
            crate::routes::vocal_tour::list_vocal_tours_response::ListVocalToursResponse,
            crate::routes::vocal_tour::get_vocal_tour_assets::VocalTourAssetsResponse,
            crate::routes::vocal_tour::list_vocal_tours_response::ExpandedVocalTour,
            crate::db::vocal_tours::VocalTour,
            crate::routes::property_contents::create_property_contents::CreatePropertyContentsRequest,
            crate::routes::property_contents::create_property_contents::CreatePropertyContentsResponse,
            crate::routes::property_contents::create_property_contents_with_studio_journey::CreatePropertyContentsWithStudioJourneyRequest,
            crate::routes::property_contents::create_property_contents_with_studio_journey::CreatePropertyContentsWithStudioJourneyResponse,
            // Studio Journey Shares
            crate::routes::studio_journey_shares::responses::CreateShareResponse,
            crate::routes::studio_journey_shares::responses::GetShareResponse,
            // Studio Tutorial Events
            crate::routes::studio::tutorial_events::TutorialEventRequest,
            crate::routes::studio::tutorial_events::TutorialEventResponse,
            // Public Journey View
            crate::routes::public::responses::get_public_journey_response::GetPublicJourneyResponse,
            crate::routes::public::responses::get_public_journey_response::PublicJourneyNodeResponse,
            // Feed schemas
            crate::routes::feed::types::CreateFeedPostRequest,
            crate::routes::feed::types::UpdateFeedPostRequest,
            crate::routes::feed::types::FeedPostResponse,
            crate::routes::feed::types::FeedPostAssetResponse,
            crate::routes::feed::types::GetFeedResponse,
            crate::db::feed_posts::FeedPost,
            crate::db::feed_post_assets::FeedPostAsset,
            // Favorited prompts schemas
            crate::db::favorited_prompts::FavoritedPrompt,
            crate::routes::user_favorites::add_favorite_prompt::AddFavoritePromptRequest,
            crate::routes::collections::create_imageboard_board::CreateImageboardBoardResponse,
            // User credit management schemas
            crate::routes::users::user_credit_handlers::DailyCreditClaimResponse,
            crate::routes::users::user_credit_handlers::DailyCreditClaimError,
            crate::schemas::user_subscription_schemas::SubscriptionStatus,
            crate::schemas::user_credit_allocation_schemas::StripePlanType,
            // Credit rewards schemas
            crate::db::credit_rewards::CreditRewardDefinition,
            crate::db::credit_rewards::UserCreditReward,
            crate::db::credit_rewards::UserCreditRewardWithDefinition,
            crate::routes::credit_rewards::claim_reward::ClaimRewardRequest,
            crate::routes::credit_rewards::claim_reward::ClaimRewardResponse,
            crate::app_constants::credits_constants::CreditRewardActionTypes,
            // Mobile Analytics schemas
            crate::routes::analytics::track_mobile_event_request::TrackMobileEventRequest,
            crate::db::analytics_events::AnalyticsEvent,
            // Dub attribution tracking schemas
            crate::routes::dub::track_lead::TrackLeadRequest,
            crate::routes::dub::track_lead::TrackLeadResponse,
            crate::routes::dub::generate_referral_token::GenerateReferralTokenResponse,
            // Imageboard webhook schemas
            crate::schemas::imageboard_schemas::WebhookErrorResponse,
            crate::schemas::imageboard_schemas::OrganizationCreditsAllocationResponse,
            crate::schemas::imageboard_schemas::OrganizationCreditsAllocationLiteResponse,
            crate::schemas::imageboard_schemas::DeductCreditsRequest,
            crate::schemas::imageboard_schemas::DeductCreditsResponse,
            crate::schemas::imageboard_schemas::BulkDeductCreditsResponse,
            crate::schemas::imageboard_schemas::BulkDeductCreditsLiteResponse,
            crate::schemas::imageboard_schemas::BillingTransactionRecord,
            crate::schemas::imageboard_schemas::FailedTransaction,
            // AgentLoop schemas
            agentloop::types::research_request::ResearchRequest,
      )
   ),
   tags(
        (name = "Auth", description = "User authentication endpoints"),
        (name = "Assets", description = "Asset management endpoints"),
        (name = "Bundles", description = "Bundle management endpoints"),
        (name = "Dashboard", description = "Dashboard and statistics endpoints"), // Added Dashboard tag
        (name = "Clone", description = "Code cloning operations"),
        (name = "Feed", description = "User feed posts management endpoints"),
        (name = "Styles", description = "Style management endpoints"),
        (name = "Formats", description = "Creative formats management endpoints"),
        (name = "Creatives", description = "Creative management endpoints"),
        (name = "Collections", description = "Creative collections management endpoints"),
        (name = "Logo Collections", description = "Logo collections management endpoints"),
        (name = "Watermarking", description = "Logo watermarking operations"),
        (name = "Requests", description = "Managing content requests"),
        (name = "Health", description = "Application health status"),
        (name = "Environment", description = "Environment variables management endpoints"),
        (name = "Files", description = "Endpoints for managing uploaded files"),
        (name = "Creative Formats", description = "Endpoints for managing creative formats"),
        (name = "API Keys", description = "API Key Management"),
        (name = "Stripe", description = "Stripe Webhook Handler"),
        (name = "Research Chat", description = "Research chat management endpoints"),
        (name = "User DB Collections", description = "User DB Collections management endpoints"),
        (name = "Research Conversations", description = "Research conversation management endpoints"),
        (name = "Documents", description = "Document management endpoints"),
        (name = "Content Studio", description = "Content creation and editing workflow endpoints"),
        (name = "Invitations", description = "Organization invitation management endpoints"),
        (name = "Organizations", description = "Organization management endpoints"),
        (name = "Infinite Research", description = "Infinite Research management endpoints"),
        (name = "Shares", description = "Object sharing management endpoints"),
        (name = "Admin", description = "Administrative endpoints"),
        (name = "User Favorites", description = "User favorites management endpoints"),
        (name = "Predefined Collections", description = "Predefined collections management endpoints"),
        (name = "One-Time Research", description = "Endpoints for one-time research tasks"),
        (name = "PDF Conversion", description = "Website to PDF conversion endpoints"),
        (name = "Vocal Tour", description = "Endpoints for the Vocal Tour workflow"),
        (name = "Property Contents", description = "Property marketing content generation endpoints"),
        (name = "Studio Journey Shares", description = "Studio Journey sharing management endpoints"),
        (name = "Public Journeys", description = "Publicly accessible endpoints for shared objects"),
        (name = "Users", description = "User management and credit claim endpoints"),
        (name = "Credit Rewards", description = "Credit reward management endpoints"),
        (name = "Dub Attribution", description = "Dub attribution tracking endpoints"),
        (name = "Imageboard", description = "Imageboard webhook endpoints"),
    ),
    info(
        title = "Reels API",
        version = "1.0.0",
        description = "API documentation for Reels API.",
        contact(
            name = "Support",
            url = "https://reels.ai",
            email = "support@reels.ai",
        ),
        license(
            name = "MIT",
            identifier = "MIT"
        )
    ),
    servers(
        (url = "/", description = "API Root")
    )
)]
pub struct ApiDoc;
